# Generated by Django 3.1 on 2020-08-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200828_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(default=26.44744),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(default=87.281248),
        ),
        migrations.AddField(
            model_name='user',
            name='search_radius',
            field=models.IntegerField(default=30),
        ),
    ]
